### ISSUE TITLE
Gnome 41.8, latest dash-to-dock, NO launchers, favorite or otherwise, showing

### ISSUE THREAD

**Issue by addieStarr** [micheleg/dash-to-dock#2029]
Basically what it says in the title, I updated and all my launchers are gone - it's just the app overview icon.

**Comment by dwconsulting** [comment]
Same here, RHEL 9.2 (x64), Gnome 40.4.0, X11 (instead of Wayland)
Tried version in Extensions site and built from source, same behavior.

**Comment by rbarbosa34** [comment]
Expecting the same behaviour with my installation as well.
Also using Wayland on Gnome 41.8 (under openSuse Leap 15.4)

**Comment by AnnikaV9** [comment]
Having this issue as well after the v82 update

System: RHEL Workstation 9.2 (Plow)
GNOME Version: 40.4.0 (Wayland)

**Comment by ingmarcosp** [comment]
I'm having the same problem on 

Opensuse Leap 15.4
Gnome 41.8
X11

If I downgrade start working again until it's updated by gnome.

How can I give you more debug info?

**Comment by Noobsai** [comment]
Hello. Error in logs:
```
JS ERROR: Exception in callback for signal: updated: TypeError: oldApps.at is not a function
_redisplay@/dash-to-dock@micxgx.gmail.com/dash.js:854:36
```
In new version changed lines 854 and 855:

```
            const oldApp = oldApps.at(oldIndex);
            const newApp = newApps.at(newIndex);
```

To fix this I just restore lines from the previous version:

```
            const oldApp = oldApps.length > oldIndex ? oldApps[oldIndex] : null;
            const newApp = newApps.length > newIndex ? newApps[newIndex] : null;
```

**Comment by AnnikaV9** [comment]
Reverting the 2 lines @Noobsai stated works here as well

**Comment by notklaatu** [comment]
I ran into this same error on RHEL 9.2 (x64), Gnome 40.4.0

Fixed with [Noobsai's solution](https://github.com/micheleg/dash-to-dock/issues/2029#issuecomment-1575258576)

**Comment by dwconsulting** [comment]
@Noobsai solution worked here as well.

**Comment by roncterry** [comment]
Confirming reverting the 2 lines @Noobsai stated works with Opensuse Leap 15.4+Gnome 41.8+X11

**Comment by addieStarr** [comment]
@Noobsai 's solution worked here as well!

**Comment by roncterry** [comment]
Can we get a new update released with those lines reverted ASAP? We have hundreds of training lab environments released in the wild using this extension that will break with no way to fix them.

**Comment by addieStarr** [comment]
I can make a PR for it if no one else will.

**Comment by addieStarr** [comment]
https://github.com/micheleg/dash-to-dock/pull/2036 Added a PR for this

> > I can make a PR for it if no one else will.
> 
> Yes, please, and thanks.

**Comment by idanka** [comment]
Yes, Fedora 38 downgrading  v81 fixes the issue.
And disable gnome extensions update (extensions-update map settings Chmode 444)

**Comment by roncterry** [comment]
As a note, this does not seem to be a problem in openSUSE Tumbleweed running Gnome 44.2. v82 of the extension works without having to change those lines. Also, changing those line does not seem to break anything as the extension keeps working after the change.

**Comment by 3v1n0** [comment]
Closed via #2036
