### ISSUE TITLE
Commit e76dfa9d breaks extension (Gnome 3.30 on Fedora 29)

### ISSUE THREAD

**Issue by slabua** [micheleg/dash-to-dock#902]
Hi, I have run git bisect to find the issue, and it appears that the commit e76dfa9d to drop the convenience library caused for me the extension not to load anymore.
I'm running gnome 3.30.2-1 on Fedora 29.
It loads fine until commit 93fc30c.

```
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:856:5
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:68:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
  
```

**Comment by micheleg** [comment]
Current master dropped support for Gnome shell <3.32 [26feddbd], so this is expected. The current updated branch for previous versions (down to 3.18) is https://github.com/micheleg/dash-to-dock/tree/gnome-3.30.

**Comment by beizhengren** [comment]
hello,how to solve it?

**Comment by slabua** [comment]
@beizhengren to move to the dedicated branch: `git checkout gnome-3.30`
